import React from 'react';
import { X, Download, FileText } from 'lucide-react';

const InvoiceModal = ({ invoice, onClose }) => {
  if (!invoice) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl w-full max-w-lg shadow-2xl relative flex flex-col overflow-hidden max-h-[90vh]">
        <div className="flex justify-between items-center p-6 border-b border-gray-100 bg-slate-50 shrink-0">
          <div className="flex items-center gap-3">
            <div className="bg-indigo-100 p-2 rounded-lg text-indigo-700">
              <FileText size={24} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-900">Invoice</h2>
              <p className="text-xs text-gray-500 font-medium mt-0.5">{invoice.invoiceNo || 'INV-PENDING'}</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 hover:bg-gray-100 p-2 rounded-full transition-colors"
          >
            <X size={20} />
          </button>
        </div>
        
        <div className="p-8 overflow-y-auto" id="invoice-content">
          <div className="flex justify-between items-start mb-8">
            <div>
              <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Billed To</p>
              <h3 className="font-bold text-gray-900 text-lg">{invoice.companyName}</h3>
              <p className="text-sm text-gray-500">Plan: {invoice.plan}</p>
              <p className="text-sm text-gray-500">Duration: {invoice.durationDays} Days</p>
            </div>
            <div className="text-right">
              <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Payment Date</p>
              <p className="font-semibold text-gray-900">
                {new Date(invoice.paymentDate).toLocaleDateString('en-US', {
                  year: 'numeric', month: 'short', day: 'numeric'
                })}
              </p>
              <div className="mt-2 inline-block px-3 py-1 bg-green-100 text-green-700 text-xs font-bold rounded-full uppercase tracking-wider">
                {invoice.status}
              </div>
            </div>
          </div>
          
          <table className="w-full text-left border-collapse mb-8">
            <thead>
              <tr className="border-b border-gray-200">
                <th className="py-3 text-xs font-bold text-gray-500 uppercase tracking-wider">Description</th>
                <th className="py-3 text-xs font-bold text-gray-500 uppercase tracking-wider text-right">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              <tr>
                <td className="py-4 text-sm text-gray-900 font-medium">
                  {invoice.plan} Plan Subscription ({invoice.durationDays} Days)
                </td>
                <td className="py-4 text-sm text-gray-900 font-medium text-right">
                  ₹{invoice.amount?.toLocaleString('en-IN') || 0}
                </td>
              </tr>
              <tr>
                <td className="py-4 text-sm text-gray-500">
                  GST (18%)
                </td>
                <td className="py-4 text-sm text-gray-500 text-right">
                  ₹{invoice.gst?.toLocaleString('en-IN') || 0}
                </td>
              </tr>
            </tbody>
            <tfoot>
              <tr className="border-t-2 border-gray-900">
                <th className="py-4 text-lg font-bold text-gray-900">Total</th>
                <th className="py-4 text-lg font-bold text-[#1E1B6E] text-right">
                  ₹{invoice.total?.toLocaleString('en-IN') || (invoice.amount || 0)}
                </th>
              </tr>
            </tfoot>
          </table>
          
          <div className="text-center text-xs text-gray-400 mt-8">
            <p>This is a computer generated invoice and does not require a signature.</p>
            <p className="mt-1">Generated by SaaS Platform System.</p>
          </div>
        </div>

        <div className="p-4 border-t border-gray-100 bg-slate-50 shrink-0 flex justify-end">
          <button 
            onClick={() => {
              // Real download logic would go here (e.g. jspdf, html2canvas)
              alert("Downloading PDF invoice...");
            }}
            className="flex items-center gap-2 px-5 py-2.5 bg-[#1E1B6E] text-white rounded-lg hover:bg-indigo-900 transition-colors font-bold text-sm"
          >
            <Download size={16} /> Download PDF
          </button>
        </div>
      </div>
    </div>
  );
};

export default InvoiceModal;
